name: Schedule Workflow

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  mensaje-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje schedule
        run: echo "Ejecucion programada"