name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      alerta:
        description: "Nivel de alerta"
        required: true
        default: "media"

jobs:
  mensaje-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar alerta
        run: echo "Workflow ejecutado manualmente"